{% set data = load_setup_py_data(setup_file='../../setup.py', from_recipe_dir=True) %}
{% set name = "das" %}
{% set version = data.get('version') %}

package:
  name: das
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"

build:
  number: 0
  entry_points:
    - das=das.cli:main
  # script: build_osx-arm64.sh  # [arm64]
  # script: build_other.sh  # [not arm64]
  script_env:
    - CONDA_OVERRIDE_CUDA=11.2

requirements:
  host:
    - python {{ python }}
    - pip
    - h5py
    - numpy>=1.22

  run:
    - python {{ python }}
    - defopt=6.3
    - rich
    - flammkuchen
    - h5py
    - matplotlib
    - matplotlib-scalebar
    - pandas
    - peakutils
    - pyyaml
    - numba::numba>=0.56.2 [not win]
    - numba::numba>=0.55.2 [win]
    - scipy
    - scikit-learn
    - scikit-image
    - tqdm
    - xarray-behave>=0.33.5
    - cudatoolkit # [win or linux]
    - cudnn # [win or linux]
    - anaconda::tensorflow==2.9.1 # [osx]
    - anaconda::tensorflow==2.9.1=cuda* # [linux]
    - anaconda::tensorflow-gpu # [win]
    - apple::tensorflow-deps # [not osx and arm64]
    - numpy>=1.22
    - ipython
    - keras-tuner  # [not arm64]

test:
  imports:
    - das
    - das.kapre
    - das.tcn
  commands:
    - das --help
    - das gui --help

about:
  home: "http://github.com/janclemenslab/das"
  license: MIT
  license_family: MIT
  license_file:
  summary: "DAS"
  doc_url: "https://janclemenslab.org/das"
  dev_url: "http://github.com/janclemenslab/das"

extra:
  recipe-maintainers:
    - postpop
