{% set data = load_setup_py_data(setup_file='../../setup.py', from_recipe_dir=True) %}
{% set name = "das" %}
{% set version = data.get('version') %}

package:
  name: das
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"

build:
  number: 0
  entry_points:
    - das=das.cli:main
  # script: build_osx-arm64.sh  # [arm64]
  # script: build_other.sh  # [not arm64]
  script_env:
    - CONDA_OVERRIDE_CUDA=11.2

requirements:
  host:
    - python {{ python }}
    - pip
  run:
    - python {{ python }}
    - rich
    - flammkuchen
    - h5py
    - matplotlib
    - pandas
    - numpy
    - numpy>=1.23  # [not win and py>39]
    - numpy<1.24  # [win and py39]
    - peakutils
    - pyyaml
    - scikit-learn
    - scikit-image
    - tqdm
    - xarray-behave>=0.34.2
    - conda-forge::cudatoolkit # [linux or win]
    - conda-forge::cudnn # [linux or win]
    - conda-forge::tensorflow<2.10 # [linux]
    - tensorflow-gpu>2.3 # [win and py<310]
    - tensorflow==2.10 # [win and py>=310]
    - anaconda::tensorflow==2.9.1 # [osx]
    - apple::tensorflow-deps # [not osx and arm64]
    - keras
    - keras-tuner  # [not arm64]

test:
  imports:
    - das
    - das.kapre
    - das.tcn
    - das.morpholayers
    - tensorflow
  commands:
    - das --help
    - das gui --help

about:
  home: "http://github.com/janclemenslab/das"
  license: MIT
  license_family: MIT
  license_file:
  summary: "DAS"
  doc_url: "https://janclemenslab.org/das"
  dev_url: "http://github.com/janclemenslab/das"

extra:
  recipe-maintainers:
    - postpop
