mode: train
batch_size: 16
num_time_steps: 4096
chunk_stride: 2048
frontend_type: stft
frontend_num_channels: 513
frontend_kernel_size: 1024
frontend_hop_seconds: 0.001
frontend_trainable: false
encoder_type: tweetynet
encoder_hidden_size: 512
encoder_num_layers: 1
encoder_kernel_size: 5
encoder_dropout: 0.1
decoder_type: linear
cross_entropy_weight: 1.0
learning_rate: 0.001
fill_gap_ms: 5.0
min_syllable_ms: 20.0
syllable_tolerance_ms: 20.0
