{% set data = load_setup_py_data(setup_file='../../setup.py', from_recipe_dir=True) %}
{% set name = "das" %}
{% set version = data.get('version') %}

package:
  name: das
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"

build:
  number: 0
  entry_points:
    - das=das.cli:main

requirements:
  host:
    - python {{ python }}
    - pip
    - h5py
    - numpy<1.24
  run:
    - python {{ python }}
    - rich
    - flammkuchen
    - matplotlib
    - pandas
    - numpy<1.24
    - peakutils
    - pyyaml
    - scikit-learn
    - scikit-image
    - tqdm
    - xarray-behave
    - apple::tensorflow-deps=2.9
    - keras
    - keras-tuner

test:
  imports:
    - das
    - das.kapre
    - das.tcn
  commands:
    - das --help
    - das gui --help

about:
  home: "http://github.com/janclemenslab/das"
  license: MIT
  license_family: MIT
  license_file:
  summary: "DAS"
  doc_url: "https://janclemenslab.org/das"
  dev_url: "http://github.com/janclemenslab/das"

extra:
  recipe-maintainers:
    - postpop
