name: Publish to Anaconda.org (win test)

on:
  release:
    types:
      - published
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
      tags:
        description: 'manual run'

jobs:
  publish:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: False
      matrix:
        python-version: [3.9, '3.10']
        os: [windows-latest]
    defaults:  # https://github.com/marketplace/actions/setup-miniconda#use-a-default-shell
      run:
        shell: bash -l {0}
    steps:
    - uses: actions/checkout@v4
    - name: Setup miniconda # https://github.com/marketplace/actions/setup-miniconda
      uses: conda-incubator/setup-miniconda@v3
      with:
        auto-update-conda: true
        channels: conda-forge,ncb,apple
        python-version: 3.12
        auto-activate-base: false
        activate-environment: anaconda-client-env
        environment-file: build_env.yml
        condarc-file: condarc.yml
    - name: Build conda package
      run: |
        conda build conda/das-test --no-test -c conda-forge -c ncb -c nvidia -c apple -c local -c ncb --python ${{ matrix.python-version }} --no-anaconda-upload
      env:
        ANACONDA_TOKEN: ${{ secrets.ANACONDA_TOKEN }}
    - name: Install and test conda package
      run: |
        conda deactivate
        conda create python=${{ matrix.python-version }} das=0.32.3 -c conda-forge -c ncb -c nvidia -c apple -c local -c ncb -n das_test -y
        conda activate das_test
        conda list
        python -c "import das; print(das.__version__)"
        das version

